const initialState = {
  loading: {
    acceptBookingLoading: false,
    declineBookingLoading: false,
    cancelBookingLoading: false,
    bookingRequestLoading: false,
    reviewLoading: false,
  },
  dashboard: {},
  loggedInUser: null,
  isAppReady: false,
  myCoords: {
    lat: null,
    lng: null,
  },
  currentLocation: null,
  notifications: [],
  pagination: {},
  property: {},
  properties: [],
  similarProperties: [],
  booking: {},
  bookings: [],
  job: {},
  jobs: [],
  similarJobs: [],
  proposals: [],
  proposal: {},
  contracts: [],
  activeTrips: [],
  trips: [],
  cards: [],
  chats: [],
  conversations: [],
  employmentHistories: [],
  rentalHistories: [],
  educations: [],
  bookmarks: [],
  myTenants: [],
  tenantProfile: {},
  transactions: [],
};

export default initialState;
